// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ComponentInterface is an autogenerated mock type for the ComponentInterface type
type ComponentInterface struct {
	mock.Mock
}

// Run provides a mock function with given fields:
func (_m *ComponentInterface) Run() (func(), func() error, error) {
	ret := _m.Called()

	var r0 func()
	if rf, ok := ret.Get(0).(func() func()); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	var r1 func() error
	if rf, ok := ret.Get(1).(func() func() error); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func() error)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}
