apiVersion: apps/v1
kind: Service
metadata:
  name: rest
  labels:
    app: rest
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: rest